name = "wm-remove-gate"
main = "src/index.ts"
compatibility_date = "2025-06-01"
workers_dev = false

[[routes]]
pattern = "eksi.biz.id/wm-remove/*"
zone_name = "eksi.biz.id"

[assets]
directory = "./ui"
run_worker_first = true
binding = "ASSETS"